### ISSUE TITLE
Is this abandonned ?

### ISSUE THREAD

**Issue by Bowarc** [steele123/mem-rs#11]

**Comment by steele123** [comment]
Hello! I still have plans on working on it in the future, just have been mostly working on "for profit" things but once I'm rich I have plans on revisiting this. It just is a project with quite a big scope that'll take quite a lot of work. I'll adjust the readme.md though to reflect the projects current status. Hope you are having a good day though :)

**Comment by steele123** [comment]
The idea overall is amazing though, rust is by far the best potential for a game hacking library, so feel free to yoink it if you'd like.
